apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.0.14
  syncPolicy:
    automated:
      prune: false
      selfHeal: true