apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-dev
  namespace: argocd
spec:
  destination:
    namespace: minio
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ChristianoPiccinin/aks-data-platform
    targetRevision: HEAD
    path: apps/dev/minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true