apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  source:
    repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 0.39.0
helm:
      values: |

        watchNamespaces:
          - kafka
        defaultClusterRole: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: false