apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-dev
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sua-org/gitops.git
    targetRevision: HEAD
    path: apps/dev/argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true