apiVersion: v2
name: monitoring
version: 1.0.0
description: Monitoring Stack
dependencies:
  - name: kube-prometheus-stack
    version: 56.6.2
    repository: https://prometheus-community.github.io/helm-charts
