apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  source:
    repoURL: https://github.com/ChristianoPiccinin/aks-data-platform.git
    chart: strimzi-kafka-operator
    targetRevision: 0.39.0
    path: apps/dev/kafka
    directory:
      recurse: true

  syncPolicy:
    automated:
      prune: false
      selfHeal: true

