apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-strimzi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ChristianoPiccinin/aks-data-platform.git
    targetRevision: HEAD
    path: charts/strimzi
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
