apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-prod
  namespace: argocd
spec:
  destination:
    namespace: spark
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ChristianoPiccinin/aks-data-platform
    targetRevision: HEAD
    path: apps/prod/spark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true