apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-prod
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sua-org/gitops.git
    targetRevision: HEAD
    path: apps/prod/kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true