apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  source:
    repoURL: https://charts.deliveryhero.io/
    chart: spark-operator
    targetRevision: 1.1.27
helm:
      values: |

        enableWebhook: false
        sparkJobNamespace: spark
  syncPolicy:
    automated:
      selfHeal: true
      prune: false