apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nats
  source:
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    chart: nats
    targetRevision: 0.19.12
helm:
      values: |

        service:
          type: NodePort
  syncPolicy:
    automated:
      selfHeal: true
      prune: false