apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pinot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/apache/pinot/master/helm
    chart: pinot
    targetRevision: main
    helm:
      releaseName: pinot
  destination:
    server: https://kubernetes.default.svc
    namespace: pinot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
