helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: monitoring
    namespace: monitoring
    version: 48.3.1
    valuesFile: values.yaml