apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  source:
    repoURL: https://googlecloudplatform.github.io/spark-on-k8s-operator
    chart: spark-operator
    targetRevision: 1.1.27
  syncPolicy:
    automated:
      prune: false
      selfHeal: true