apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/seu-org/data-platform
    targetRevision: main
    path: argo/base/strimzi
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
